/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const GM: typeof import('vite-plugin-monkey/dist/client')['GM']
  const GM_addElement: typeof import('vite-plugin-monkey/dist/client')['GM_addElement']
  const GM_addStyle: typeof import('vite-plugin-monkey/dist/client')['GM_addStyle']
  const GM_addValueChangeListener: typeof import('vite-plugin-monkey/dist/client')['GM_addValueChangeListener']
  const GM_cookie: typeof import('vite-plugin-monkey/dist/client')['GM_cookie']
  const GM_deleteValue: typeof import('vite-plugin-monkey/dist/client')['GM_deleteValue']
  const GM_deleteValues: typeof import('vite-plugin-monkey/dist/client')['GM_deleteValues']
  const GM_download: typeof import('vite-plugin-monkey/dist/client')['GM_download']
  const GM_getResourceText: typeof import('vite-plugin-monkey/dist/client')['GM_getResourceText']
  const GM_getResourceURL: typeof import('vite-plugin-monkey/dist/client')['GM_getResourceURL']
  const GM_getTab: typeof import('vite-plugin-monkey/dist/client')['GM_getTab']
  const GM_getTabs: typeof import('vite-plugin-monkey/dist/client')['GM_getTabs']
  const GM_getValue: typeof import('vite-plugin-monkey/dist/client')['GM_getValue']
  const GM_getValues: typeof import('vite-plugin-monkey/dist/client')['GM_getValues']
  const GM_info: typeof import('vite-plugin-monkey/dist/client')['GM_info']
  const GM_listValues: typeof import('vite-plugin-monkey/dist/client')['GM_listValues']
  const GM_log: typeof import('vite-plugin-monkey/dist/client')['GM_log']
  const GM_notification: typeof import('vite-plugin-monkey/dist/client')['GM_notification']
  const GM_openInTab: typeof import('vite-plugin-monkey/dist/client')['GM_openInTab']
  const GM_registerMenuCommand: typeof import('vite-plugin-monkey/dist/client')['GM_registerMenuCommand']
  const GM_removeValueChangeListener: typeof import('vite-plugin-monkey/dist/client')['GM_removeValueChangeListener']
  const GM_saveTab: typeof import('vite-plugin-monkey/dist/client')['GM_saveTab']
  const GM_setClipboard: typeof import('vite-plugin-monkey/dist/client')['GM_setClipboard']
  const GM_setValue: typeof import('vite-plugin-monkey/dist/client')['GM_setValue']
  const GM_setValues: typeof import('vite-plugin-monkey/dist/client')['GM_setValues']
  const GM_unregisterMenuCommand: typeof import('vite-plugin-monkey/dist/client')['GM_unregisterMenuCommand']
  const GM_webRequest: typeof import('vite-plugin-monkey/dist/client')['GM_webRequest']
  const GM_xmlhttpRequest: typeof import('vite-plugin-monkey/dist/client')['GM_xmlhttpRequest']
  const cls: typeof import('tagged-classnames-free')['cls']
  const createIntegratedUi: typeof import('@/helpers/ui/integrated')['createIntegratedUi']
  const createRef: typeof import('react')['createRef']
  const createShadowRootUi: typeof import('@/helpers/ui/shadow-root')['createShadowRootUi']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const monkeyWindow: typeof import('vite-plugin-monkey/dist/client')['monkeyWindow']
  const reactRenderInShadowRoot: typeof import('@/helpers/react/shadow-root-helpers')['reactRenderInShadowRoot']
  const startTransition: typeof import('react')['startTransition']
  const tw: typeof import('tagged-classnames-free')['tw']
  const unsafeWindow: typeof import('vite-plugin-monkey/dist/client')['unsafeWindow']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ShadowRootUi } from '@/helpers/ui/shadow-root.ts'
  import('@/helpers/ui/shadow-root.ts')
}
